version: 2

general:
  branches:
    only:
      - staging

jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
    working_directory: '~/wafflecone'
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python -m virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
            sudo pip install awscli --upgrade
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ./venv
      - run:
          name: Package and Deploy Django app using Zappa
          command: |
            source venv/bin/activate
            zappa update staging
      - run:
          name: Upload Environment Variables to AWS Lambda function
          command: |
            bash uploadEnvs.sh staging
      - run:
          name: Run database migration
          command: |
            source venv/bin/activate
            zappa manage staging migrate
