version: 2

general:
  branches:
    only:
      - staging
      - ci-test

jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
    working_directory: '~/wafflecone'
    environment:

    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python -m virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
            sudo pip install boto3
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ./venv
      - run:
          name: Package and Deploy Django app using Zappa
          command: |
            source venv/bin/activate
            if [ "${CIRCLE_BRANCH}" == "ci-test" ]; then
              zappa update staging
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              zappa update staging
            fi
      - run:
          name: Upload Environment Variables to AWS Lambda function
          command: |
            if [ "${CIRCLE_BRANCH}" == "ci-test" ]; then
              python ./transformEnvs.py staging
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              python ./transformEnvs.py staging
            fi
      - run:
          name: Run database migration
          command: |
            source venv/bin/activate
            if [ "${CIRCLE_BRANCH}" == "ci-test" ]; then
              zappa manage staging migrate
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              zappa manage staging migrate
            fi
